development:
  adapter: postgresql
  database: ios_link_convert_development
  pool: 5
  timeout: 5000
  host: localhost
  
test:
  adapter: postgresql
  database: ios_link_convert_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ios_link_convert_production
  pool: 5
  timeout: 5000







